// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class Destination
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Photo { get; set; }

    public int Dicount { get; set; }

    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}