// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class Guest
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<TourBooking> TourBookings { get; set; } = new List<TourBooking>();

    public virtual ICollection<TransferBooking> TransferBookings { get; set; } = new List<TransferBooking>();
}