// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class TourPhoto
{
    public int Id { get; set; }

    public int TourId { get; set; }

    public string Photo { get; set; }

    public virtual Tour Tour { get; set; }
}