// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class Tour
{
    public int Id { get; set; }

    public int DestinationId { get; set; }

    public int TourTypeId { get; set; }

    public string Duration { get; set; }

    public decimal AdultPrice { get; set; }

    public decimal ChildPrice { get; set; }

    public int Discount { get; set; }

    public string MainPhoto { get; set; }

    public virtual Destination Destination { get; set; }

    public virtual ICollection<TourBooking> TourBookings { get; set; } = new List<TourBooking>();

    public virtual ICollection<TourLocalized> TourLocalizeds { get; set; } = new List<TourLocalized>();

    public virtual ICollection<TourPhoto> TourPhotos { get; set; } = new List<TourPhoto>();

    public virtual TourType TourType { get; set; }
}