// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class TourBooking
{
    public int Id { get; set; }

    public int TourId { get; set; }

    public int GuestId { get; set; }

    public DateOnly TripDate { get; set; }

    public int Adults { get; set; }

    public int Children { get; set; }

    public string Nationality { get; set; }

    public string SpecialRequest { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Guest Guest { get; set; }

    public virtual Tour Tour { get; set; }
}