// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class TourTypeLocalized
{
    public int LanguageId { get; set; }

    public int TourTypeId { get; set; }

    public string Name { get; set; }

    public virtual Language Language { get; set; }

    public virtual TourType TourType { get; set; }
}