// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sunny_Hurghada.Models;

public partial class TransferBooking
{
    public int Id { get; set; }

    public int GuestId { get; set; }

    public string Destination { get; set; }

    public string PickUpLocation { get; set; }

    public int Adults { get; set; }

    public int Children { get; set; }

    public DateTime PickUpDateTime { get; set; }

    public string SpecialRequest { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Guest Guest { get; set; }
}